In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/2019-Nov.csv")
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [ ]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nInfo:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nEvent types:")
print(df["event_type"].value_counts())

Shape: (67501979, 9)

Columns:
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67501979 entries, 0 to 67501978
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 4.5+ GB
None

Missing values:
event_time              0
event_type              0
product_id              0
category_id             0
category_code    21898171
brand             9224078
price                   0
user_id                 0
user_session           10
dtype: int64



Event types:
event_type
view        63556110
cart         3028930
purchase      916939
Name: count, dtype: int64

In [5]:
df_sample = df.sample(n=50000, random_state=42)
df_sample.to_csv("../data/2019-Nov-sample.csv", index=False)

In [ ]:
df.dtypes

event_time        object
event_type        object
product_id         int64
category_id        int64
category_code     object
brand             object
price            float64
user_id            int64
user_session      object
dtype: object

In [12]:
df.isnull().sum().sort_values(ascending=False)

category_code    21898171
brand             9224078
user_session           10
event_time              0
event_type              0
category_id             0
product_id              0
price                   0
user_id                 0
dtype: int64

In [ ]:
df['user_session'].nunique()

13776050

In [ ]:
df['user_id'].nunique()

3696117

In [15]:
df.groupby('event_type')["user_session"].nunique()

event_type
cart         1743342
purchase      773214
view        13766768
Name: user_session, dtype: int64

In [17]:
sample_sessions = df["user_session"].dropna().unique()[:3]
sample_sessions
for session in sample_sessions:
    print(f"\nSession: {session}")
    display(
        df[df["user_session"] == session]
        .sort_values("event_time")
        .head(20)
    )

Session: 4d3b30da-a5e4-49df-b1a8-ba5943f1dd33

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
95,2019-11-01 00:00:36 UTC,view,1004184,2053013555631882655,electronics.smartphone,xiaomi,463.15,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
121,2019-11-01 00:00:47 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
131,2019-11-01 00:00:50 UTC,view,1005234,2053013555631882655,electronics.smartphone,xiaomi,398.72,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
263,2019-11-01 00:01:48 UTC,view,1003898,2053013555631882655,electronics.smartphone,oneplus,540.30,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
329,2019-11-01 00:02:17 UTC,view,1003898,2053013555631882655,electronics.smartphone,oneplus,540.30,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
352,2019-11-01 00:02:24 UTC,view,1003499,2053013555631882655,electronics.smartphone,oneplus,461.61,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
397,2019-11-01 00:02:41 UTC,view,1003499,2053013555631882655,electronics.smartphone,oneplus,461.61,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
416,2019-11-01 00:02:48 UTC,view,1003898,2053013555631882655,electronics.smartphone,oneplus,540.30,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33

Session: 8e5f4f83-366c-4f70-860e-ca7417414283

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283

Session: 755422e7-9040-477b-9bd2-6a6e8fd97387

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
83,2019-11-01 00:00:28 UTC,view,17301495,2053013553853497655,NaN,chanel,171.17,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
116,2019-11-01 00:00:44 UTC,view,17301611,2053013553853497655,NaN,NaN,47.32,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
155,2019-11-01 00:01:02 UTC,view,17301421,2053013553853497655,NaN,givenchy,77.22,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
264,2019-11-01 00:01:48 UTC,view,17301457,2053013553853497655,NaN,givenchy,72.60,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
342,2019-11-01 00:02:21 UTC,view,17300705,2053013553853497655,NaN,lanvin,56.14,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
371,2019-11-01 00:02:29 UTC,view,17301127,2053013553853497655,NaN,NaN,55.94,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
508,2019-11-01 00:03:26 UTC,view,17301129,2053013553853497655,NaN,NaN,87.00,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
552,2019-11-01 00:03:47 UTC,view,17301653,2053013553853497655,NaN,lacoste,42.51,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
654,2019-11-01 00:04:25 UTC,view,17302789,2053013553853497655,NaN,givenchy,59.57,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
698,2019-11-01 00:04:47 UTC,view,17301725,2053013553853497655,NaN,NaN,14.47,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387

In [20]:
session_event_counts = pd.crosstab(df["user_session"], df["event_type"])

In [21]:
session_event_counts.head()

event_type                            cart  purchase  view
user_session
0000007c-adbf-4ed7-af17-d1fef9763d67     0         0     1
0000009d-1f5b-40b9-bd23-db4f3d973ae3     0         0     1
000001d5-f8f8-4e40-b8d6-224155713521     0         0     1
00000510-834a-498a-9bed-561a90c5125e     0         0     1
00000616-f016-4c01-b323-438486d9d3ee     0         0     8

In [22]:
session_time = df.groupby("user_session")["event_time"].agg(["min", "max"])
session_time.head()

,min,max
user_session,,
0000007c-adbf-4ed7-af17-d1fef9763d67,2019-11-18 09:16:19 UTC,2019-11-18 09:16:19 UTC
0000009d-1f5b-40b9-bd23-db4f3d973ae3,2019-11-13 06:02:54 UTC,2019-11-13 06:02:54 UTC
000001d5-f8f8-4e40-b8d6-224155713521,2019-11-09 13:58:06 UTC,2019-11-09 13:58:06 UTC
00000510-834a-498a-9bed-561a90c5125e,2019-11-02 13:29:04 UTC,2019-11-02 13:29:04 UTC
00000616-f016-4c01-b323-438486d9d3ee,2019-11-17 05:35:46 UTC,2019-11-17 05:39:59 UTC

In [ ]:
session_time["min"] = pd.to_datetime(session_time["min"])
session_time["max"] = pd.to_datetime(session_time["max"])
session_time["session_duration_sec"] = (
    session_time["max"] - session_time["min"]
).dt.total_seconds()

In [26]:
session_time.head()

,min,max,session_duration_sec
user_session,,,
0000007c-adbf-4ed7-af17-d1fef9763d67,2019-11-18 09:16:19+00:00,2019-11-18 09:16:19+00:00,0.0
0000009d-1f5b-40b9-bd23-db4f3d973ae3,2019-11-13 06:02:54+00:00,2019-11-13 06:02:54+00:00,0.0
000001d5-f8f8-4e40-b8d6-224155713521,2019-11-09 13:58:06+00:00,2019-11-09 13:58:06+00:00,0.0
00000510-834a-498a-9bed-561a90c5125e,2019-11-02 13:29:04+00:00,2019-11-02 13:29:04+00:00,0.0
00000616-f016-4c01-b323-438486d9d3ee,2019-11-17 05:35:46+00:00,2019-11-17 05:39:59+00:00,253.0